Lesson 01
AlexPFrank/development pull request #2
Opened 2018-11-08 22:58 UTC by AlexPFrank

The first lesson is done :)

2018-11-09 09:36 UTC, timchukd requested changes
good job! but please check my comments :)

2018-11-09 09:36 UTC, timchukd commented on Task1.html
> +			.ac{
Please do not use short variables name in the code. We are writing the code for the each other and good when from the first look is clear what the developer mean. Optimization stuff like make from long variable names -> short is job of builders.

2018-11-09 09:36 UTC, timchukd commented on Task1.html
> +			.underline{
this class is not use in your code

2018-11-09 09:36 UTC, timchukd commented on Task1.html
> +			.linethrough{
this class is not use in your code

2018-11-09 09:36 UTC, timchukd commented on Task1.html
> +			.ad{
this class is not use in your code

2018-11-09 09:36 UTC, timchukd commented on Task1.html
> +
unneeded line

2018-11-09 09:36 UTC, timchukd commented on Task1.html
> +		<p>It's a text, that I've prepared for Task-1. This sentence is used for example of <strong>bold</strong> style of words. This sentence is used for example of <em>curve</em> style of words. This se
please do not write everything in one line
limit is 100 characters (this is +/- the width of the screen)

I guess this way looks better for the reader:
```
<p>
    It's a text, that I've prepared for Task-1. This sentence is used for example of 
    <strong>bold</strong> style of words. This sentence is used for example of 
    <em>curve</em> style of words. 
    This sentence is used for example of <a class="underline">underlined</a> style of words. 
    And this sentence is used for example of <a class="linethrough">NOT</a> linedthrough style of words.
<p>
```

P.S. please check code in the bottom

2018-11-09 09:36 UTC, timchukd commented on Task2.html
> +
unneeded space

2018-11-09 09:36 UTC, timchukd commented on Task2.html
> +		<img src="http://www.kurzweilai.net/images/Naam-Limits-of-Earth-Part1-001-earth-600x600.jpg" height="400" width="400" style="float: left" style="padding: 7px 7px 7px 7px"><p>It's a text, which I've
this tag should be inside body

2018-11-09 09:36 UTC, timchukd commented on Task3.html
> +
unneeded line

2018-11-09 09:36 UTC, timchukd commented on Task3.html
> +		<h3><a style="text-decoration: underline">It's a first part of the task 3:</a> SO<sub>2</sub> + NaOH = Na<sub>2</sub>SO<sub>3</sub> + H<sub>2</sub>O</h3>
please do not write all in one line
p.s. please check rest of the tasks and fix it

2018-11-09 09:36 UTC, timchukd commented on Task4.html
> +
unneeded line

2018-11-09 09:36 UTC, timchukd commented on Task4.html
> +			.ac{
please check previous comment about short variable name

2018-11-09 09:45 UTC, AlexPFrank commented
OK, I'll fix it as soon as I'll be able to do it

2018-11-12 10:13 UTC, AlexPFrank commented on Task1.html
> +			.underline{
This class is used in the first paragraph (<p>........<a = class"underline">.........</a>..........</p>)

2018-11-12 10:14 UTC, AlexPFrank commented on Task1.html
> +			.linethrough{
This class is also used in the same paragraph like class "underline"

2018-11-12 10:15 UTC, AlexPFrank commented on Task1.html
> +			.ad{
It was fixed

2018-11-12 10:15 UTC, AlexPFrank commented on Task1.html
> +
It was fixed

2018-11-12 10:15 UTC, AlexPFrank commented on Task2.html
> +		<img src="http://www.kurzweilai.net/images/Naam-Limits-of-Earth-Part1-001-earth-600x600.jpg" height="400" width="400" style="float: left" style="padding: 7px 7px 7px 7px"><p>It's a text, which I've
It was fixed

2018-11-12 10:15 UTC, AlexPFrank commented on Task3.html
> +
It was fixed

2018-11-12 10:15 UTC, AlexPFrank commented on Task3.html
> +		<h3><a style="text-decoration: underline">It's a first part of the task 3:</a> SO<sub>2</sub> + NaOH = Na<sub>2</sub>SO<sub>3</sub> + H<sub>2</sub>O</h3>
It was fixed

2018-11-12 10:15 UTC, AlexPFrank commented on Task4.html
> +
It was fixed

2018-11-12 10:15 UTC, AlexPFrank commented on Task4.html
> +			.ac{
It was fixed

2018-11-12 10:16 UTC, AlexPFrank commented on Task1.html
> +			.ac{
It was fixed

2018-11-12 10:58 UTC, timchukd commented on Task1.html
> +			.underline{
ok

2018-11-12 10:58 UTC, timchukd commented on Task1.html
> +			.linethrough{
ok

2018-11-12 10:59 UTC, timchukd approved these changes

2018-11-12 11:00 UTC, timchukd commented
good to go! 👍 

p.s. "It was fixed": you could write just "fixed" it means the same

2018-11-12 11:02 UTC, merged