Lesson#2
AlexPFrank/development pull request #3
Opened 2018-11-18 16:38 UTC by AlexPFrank

Lesson#2 completed

2018-11-19 14:57 UTC, timchukd requested changes
looks nice 👍 

please fix few findings, please delete task1 - 4 from root directory and good to go ;)

2018-11-19 14:57 UTC, timchukd commented on Lesson#2/Task2.html
> +	<title>Lesson#2 Task4</title>
task2 should be in the title

2018-11-19 14:57 UTC, timchukd commented on Lesson#2/Task3.html
> +		<br/>
second tag <br/> is not needed here
if you want to add more space, you should do it with styles to add margin-bottom for example

p.s. please check rest of the code

2018-11-22 07:01 UTC, AlexPFrank commented on Lesson#2/Task2.html
> +	<title>Lesson#2 Task4</title>
Fixed

2018-11-22 07:01 UTC, AlexPFrank commented on Lesson#2/Task3.html
> +		<br/>
Fixed

2018-11-22 11:07 UTC, timchukd approved these changes

2018-11-22 11:07 UTC, timchukd commented
merge it

2018-11-22 11:13 UTC, merged